--- #YAML:1.0
name:         MIME-EncWords
abstract:     deal with RFC 2047 encoded words (improved)
version:      1.012
author:
  - Hatuka*nezumi - IKEDA Soji <hatuka@nezumi.nu>
license:      perl
distribution_type: module
requires:
    Encode:                        1.98
    MIME::Base64:                  2.13
    MIME::Charset:                 1.007.1
    perl:                          5.005
build_requires:
    Test::More:                    0
provides:
    MIME::EncWords:
        file:                      EncWords.pm
        version:                   1.012
resources:
    repository: http://hatuka.nezumi.nu/repos/MIME-EncWords/
meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: author

