# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MIME-EncWords
version:      0.032
version_from: EncWords.pm
installdirs:  site
requires:
    Encode:                        1.98
    MIME::Base64:                  2.13
    MIME::Charset:                 0.04.1
    Test:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
